language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: 3XU4ojkoHyJi83f2On9DjxiECWKSB5krPKh2bhuqo3Y8gktiZHdRrBs4G134BAAa0BbMse6a/BxvhmXiuSQC2ktfnhyWN2udVrJSxBV5M8PrM3kHFVg1zgXq+F0WkuADxgAk6g8Jc9GIvvMON0R3dkTbkojyRFIjDiTmTMAa3Mfg2l0zoJGMJg3qqxYfiH7Wa8YlqCm5MCXgnBi3J5rYBHvqcs+pAy1lav2Z1KOC6y0cJnu79px4KLR3Ek6AHzpqzG2c+eAtCKKINS+2qzoCixgD603iHeTzBr+wSTpTQ2yjVLDr375dSXrXkr3NdMY+69l+gqsilZ6Xt4rIoJfidSnhD0Vy3ZGyohshSXFtdn2MXRlvVoOZpT2y6WdmJpDu24pJHsYBIzQZrDx8lCUeNv6dJ8zsCUeJ/fihcmN01OCEeeBNO/4mPau4FGFeHw9u7GF00KFcCOWIaiF8am7b/0P7Gw6EHaEV/5XAhDnFRKHXWmNTjemvPeuJhQFlYijRGRvp8qADGWYIPVfS0RLpf1XoC+hrcfsOh0+YYwkoEh/85Vd3GdFDdM3RCvbl6XKS9c25lC3Qxhr3VQ6bHhc9WdSCplZmCYQRZ98854CfCYA/FzIA9LJlYFANMW7aYxkLZfo77ZfZK4eZcEGZyKMj8SpMP7u9F+iUWXrAbzlZaa4=
  app: git@heroku.com:capstone-node.git
  on:
    repo: pcyu/capstone-node
