language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: mOSiYmj9LErxa9I1WJfC7FmywLyfN1jNLLm8sqE1qLmYD+bz+ZNiH0XlrK3xanXkIqKrA064O/iSPFjy1o6XlXIJCcxSPYW5bf2yG5ivzMD40n2hxZYWcyR13KnDsnmSj4tKuXHu2LIzgkN6rQ3lXffopYj7i0afEvD+Pn6PngrXgB/HqyTi87TbQ2lxx78pfFl1AiY5EuF1KMhiKNYBEkF5Z953C5e7r4TGCTzyXX5IuKIE00mOOqczHgMWMI9Anqo1z6+VQ071esNw1NJxw19rwpL/Cj7fTtCNAPgPJMmNACAREbYSbIjgJ/hcr0NSnotTQuZ3yil3dvH9iWREU8fU0wIu+fSbt0/C7Exl/iSnVoD/mTzrr0qqNadkbv46MZvK6EjuM6nedc7Pd4IvmOKo8QDmu/SEm8Ds8ShfHGhPb3S6r8zL5oCHJP1L//p2sdfgkf5iqVU//kLWNIkk3jnHQbfx5A8OjchP0SsgP2Tlncfp9u1ctHYDc/9PrITW6RiTmumoQ7JH4HaZhF9zlkZlQXRwtPmFGhPIPVPuMVwAflSUQErRIiKF9PbymP+zMMST7D+AluLFN4pQ8wl3me1FH6L+Dt3JLtphzYPXzZmb++zjln2JQoU/KfKvXbByEyYjW5E5QxK3FI/bJ7USnYiqrGIkzbueBC4r2HunTaQ=
  app: capstone-node-pcyu
  on:
    repo: pcyu/capstone-node
